name: CI

on: [push]

jobs:
  build-test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: "7.1"
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: build/config/phpunit.xml
          args: --coverage-text
